// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ja508yAYqzYrVGIt16VqjaLvEnQsVGQ',
    appId: '1:972503944615:web:b9a9f2626f447ea4de3a82',
    messagingSenderId: '972503944615',
    projectId: 'clositta',
    authDomain: 'clositta.firebaseapp.com',
    storageBucket: 'clositta.firebasestorage.app',
    measurementId: 'G-L6BW3QQ5MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8XB-Bn4MCQsizjVa-6TW_7GM-1XcgE1U',
    appId: '1:972503944615:android:047abf1c53add84ade3a82',
    messagingSenderId: '972503944615',
    projectId: 'clositta',
    storageBucket: 'clositta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv97QOhzmndnEPcxO7OHTXiZRMDbgVu8c',
    appId: '1:972503944615:ios:3eedff143a1b2512de3a82',
    messagingSenderId: '972503944615',
    projectId: 'clositta',
    storageBucket: 'clositta.firebasestorage.app',
    androidClientId: '972503944615-tm2j1r9sisops3ka94tpe5qt5lv7fq7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chicora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv97QOhzmndnEPcxO7OHTXiZRMDbgVu8c',
    appId: '1:972503944615:ios:3eedff143a1b2512de3a82',
    messagingSenderId: '972503944615',
    projectId: 'clositta',
    storageBucket: 'clositta.firebasestorage.app',
    androidClientId: '972503944615-tm2j1r9sisops3ka94tpe5qt5lv7fq7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chicora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ja508yAYqzYrVGIt16VqjaLvEnQsVGQ',
    appId: '1:972503944615:web:5b50ba23999d886bde3a82',
    messagingSenderId: '972503944615',
    projectId: 'clositta',
    authDomain: 'clositta.firebaseapp.com',
    storageBucket: 'clositta.firebasestorage.app',
    measurementId: 'G-RZFZV0KBGZ',
  );
}
